import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font.normal]
family = "JetbrainsMono Nerd Font Mono"
style = "Regular"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
opacity = 0.8

